### ISSUE TITLE
here没反应

### ISSUE THREAD

**Issue by ghost** [TISUnion/Here#12]
不知道为什么已经加载模组了!!here没有反应

**Comment by ghost** [comment]
以下是错误代码
[MCDR] [06:56:18] [PT0-on_info@Here/ERROR]: Error calling on_info in plugin Here
Traceback (most recent call last):
  File "D:\mcdr\utils\plugin_thread.py", line 41, in run
    task_data.func(*task_data.args)
  File "plugins\Here.py", line 45, in on_info
    dimension = int(re.search(r'(?<=Dimension: )-?\d', info.content).group())
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by ghost** [comment]
emm脑洞一开改了代码里的here_user就好了。。。
